### ISSUE TITLE
Add pdf/png schematic to the repository

### ISSUE THREAD

**Issue by jaxxzer** [AirFleetTeam/FOC_ESC-hardware#1]
In order to facilitate the participation of others who do not have Altium Designer, please add the schematic diagram in a rendered format.

**Comment by DusKing1** [comment]
check this? https://github.com/AirFleetTeam/FOC_ESC-hardware/blob/master/files/FOC_ESC%20Schematic%20V1.0.pdf

**Comment by jaxxzer** [comment]
I'm so sorry, I missed it when I was looking. I thought this was part of the altium files in the same directory.
