### ISSUE TITLE
Pulldown resistors are not necessary

### ISSUE THREAD

**Issue by jaxxzer** [AirFleetTeam/FOC_ESC-hardware#4]
R2, R5 etc. are not necessary, they are built into the bridge driver in the SOC
See: [datasheet](https://active-semi.com/wp-content/uploads/PAC5523_Datasheet.pdf
)
- Figure 12-2 Typical Gate Driver Connections
- Figure 12-3 High-Side Switching Transients and Optional Circuitry

![image](https://user-images.githubusercontent.com/8315108/57206898-5519a680-6f97-11e9-9449-6482d5eade0a.png)

**Comment by DusKing1** [comment]
That's our fault. I'll change that.

**Comment by DusKing1** [comment]
Done in v1.1
