### ISSUE TITLE
Break out serial interface

### ISSUE THREAD

**Issue by jaxxzer** [AirFleetTeam/FOC_ESC-hardware#6]
Pwm/single wire input is not convenient for testing or as a single interface. Please add support for additional serial communication interfaces. I suggest simply breaking out to test pads or otherwise pins PE0~PE3.

This will allow spi, uart, i2c and can according to Table 18-1 PAC5523 Peripheral Pin MUX:

https://active-semi.com/wp-content/uploads/PAC5523_Datasheet.pdf

**Comment by DusKing1** [comment]
Done in v1.1

**Comment by jaxxzer** [comment]
We may close it then?

**Comment by DusKing1** [comment]
yeah
